apiVersion: v2
name: "cray-power-control"
version: 2.1.11
description: "Kubernetes resources for cray-power-control"
home: "https://github.com/Cray-HPE/hms-power-control-charts"
sources:
  - "https://github.com/Cray-HPE/hms-power-control"
dependencies:
  - name: cray-service
    version: "~11.0"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
  - name: cray-etcd-base
    version: "~1.2"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
maintainers:
  - name: Hardware Management
    url: https://github.com/orgs/Cray-HPE/teams/hardware-management
appVersion: 2.7.0  # update pprof image version below as well
annotations:
  artifacthub.io/images: |-
    - name: cray-power-control-pprof
      image: artifactory.algol60.net/csm-docker/stable/cray-power-control-pprof:2.7.0
  artifacthub.io/license: "MIT"
